version: '3'

services:
  proxy:
    image: traefik
    ports:
      - '80:80'
      - '443:443'
    networks:
      - ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${SRV_APPDATA}/resources/traefik.toml:/etc/traefik/traefik.toml:ro
      - ${SRV_APPDATA}/logs/:/var/log/traefik/:rw
      - ${SRV_APPDATA}/persistent/acme.json:/etc/traefik/acme/acme.json:rw
    environment:
      - DO_AUTH_TOKEN=083bc666dd915ad0e0b754f5e32c3b5809cc86fbb26defe1fbc49f6446ae9977
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.docker.network=revprox_ingress"
        - "traefik.port=8080"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.terry.cloud"

networks:
  # network that all web exposed containers should connect to
  # such that traefix proxy can forward requests
  ingress:
    driver: overlay
