################################################################
# Entrypoints
defaultEntryPoints = ["http", "https"]

[entrypoints]
	[entrypoint.http]
		address=":80"
		compress=true
	[entrypoint.https]
		address=":443"
################################################################



################################################################
# Logging
logLevel="INFO"

[traefikLog]
filePath = "/var/log/traefik/traefik.log"
format = "json"

[accessLog]
filePath = "/var/log/traefik/access.log"
format = "json"
################################################################



################################################################
# enable web gui
[api]
################################################################



################################################################
# Enable Docker Swarm Provider
[docker]

endpoint = "unix:///var/run/docker.sock"

# Default domain - overide by setting the "traefik.domain" label on a service
domain = "terry.cloud"

# Watch for changes to services, etc
watch = true

# Use Docker Swarm Mode as data provider.
swarmMode = true

# Expose services unless specified otherwise
exposedByDefault = true
################################################################