config:
  # Default domain used for exposed services
  default_domain : example.com

  # Email used for letsencrypt certificates
  acme_email     : bob@example.com

  # Domain at which the traefik GUI can be accessed
  frontend_domain: traefik.example.com

  # Domain at which the consul GUI/API can be accessed
  consul_domain: consul.example.com

  # Whether consul agent should also be exposed to the docker host running
  # the container. Setting to true will be a security vulnerability if the
  # host is publically exposed and no further actions are taken, for example
  # setting up IP tables to block access from WAN
  expose_to_host: false
