hosts:
  traefix_gui:
    domain: traefix.swarm-name.terry.cloud
    # Generate with command like: echo $(htpasswd -nb <AUTH-USER> <AUTH-PASS>) | sed -e s/\\$/\\$\\$/g
    # Need to escape $ with preceeding $
    # see: https://medium.com/@techupbusiness/add-basic-authentication-in-docker-compose-files-with-traefik-34c781234970
    htpasswd: 'jt:$$apr1$$c1ThCiY8$$Es6dm/poqDjmV6nuoOZz5/'
